# TCL File Generated by Component Editor 16.0
# Wed Jun 21 11:54:03 PDT 2017
# DO NOT MODIFY


# 
# protobuf_serializer "Protocol Buffer Serializer" v3.0
# Mario Admon 2017.06.21.11:54:03
# RTL for a protobuf serialization HW accelerator
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module protobuf_serializer
# 
set_module_property DESCRIPTION "RTL for a protobuf serialization HW accelerator"
set_module_property NAME protobuf_serializer
set_module_property VERSION 3.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Custom IP"
set_module_property AUTHOR "Mario Admon"
set_module_property DISPLAY_NAME "Protocol Buffer Serializer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL protobuf_serializer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file protobuf_serializer.v VERILOG PATH ../protobuf-serializer/protobuf_serializer.v
add_fileset_file varint_in_fifo.qsys OTHER PATH ../protobuf-serializer/varint_in_fifo.qsys
add_fileset_file varint_in_index.qsys OTHER PATH ../protobuf-serializer/varint_in_index.qsys
add_fileset_file varint_in_size.qsys OTHER PATH ../protobuf-serializer/varint_in_size.qsys
add_fileset_file raw_data_in_fifo.qsys OTHER PATH ../protobuf-serializer/raw_data_in_fifo.qsys
add_fileset_file raw_data_in_index.qsys OTHER PATH ../protobuf-serializer/raw_data_in_index.qsys
add_fileset_file raw_data_in_wstrb.qsys OTHER PATH ../protobuf-serializer/raw_data_in_wstrb.qsys
add_fileset_file varint_out_fifo.qsys OTHER PATH ../protobuf-serializer/varint_out_fifo.qsys
add_fileset_file varint_out_index.qsys OTHER PATH ../protobuf-serializer/varint_out_index.qsys
add_fileset_file raw_data_out_fifo.qsys OTHER PATH ../protobuf-serializer/raw_data_out_fifo.qsys
add_fileset_file raw_data_out_index.qsys OTHER PATH ../protobuf-serializer/raw_data_out_index.qsys
add_fileset_file out_fifo.qsys OTHER PATH ../protobuf-serializer/out_fifo.qsys
add_fileset_file fsm_0.v VERILOG PATH ../protobuf-serializer/fsm_0.v
add_fileset_file fsm_1.v VERILOG PATH ../protobuf-serializer/fsm_1.v
add_fileset_file fsm_2.v VERILOG PATH ../protobuf-serializer/fsm_2.v
add_fileset_file fsm_3a.v VERILOG PATH ../protobuf-serializer/fsm_3a.v
add_fileset_file fsm_3b.v VERILOG PATH ../protobuf-serializer/fsm_3b.v
add_fileset_file fsm_3.v VERILOG PATH ../protobuf-serializer/fsm_3.v
add_fileset_file fsm_4.v VERILOG PATH ../protobuf-serializer/fsm_4.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL protobuf_serializer
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file protobuf_serializer.v VERILOG PATH ../protobuf-serializer/protobuf_serializer.v
add_fileset_file varint_in_fifo.qsys OTHER PATH ../protobuf-serializer/varint_in_fifo.qsys
add_fileset_file varint_in_index.qsys OTHER PATH ../protobuf-serializer/varint_in_index.qsys
add_fileset_file varint_in_size.qsys OTHER PATH ../protobuf-serializer/varint_in_size.qsys
add_fileset_file raw_data_in_fifo.qsys OTHER PATH ../protobuf-serializer/raw_data_in_fifo.qsys
add_fileset_file raw_data_in_index.qsys OTHER PATH ../protobuf-serializer/raw_data_in_index.qsys
add_fileset_file raw_data_in_wstrb.qsys OTHER PATH ../protobuf-serializer/raw_data_in_wstrb.qsys
add_fileset_file varint_out_fifo.qsys OTHER PATH ../protobuf-serializer/varint_out_fifo.qsys
add_fileset_file varint_out_index.qsys OTHER PATH ../protobuf-serializer/varint_out_index.qsys
add_fileset_file raw_data_out_fifo.qsys OTHER PATH ../protobuf-serializer/raw_data_out_fifo.qsys
add_fileset_file raw_data_out_index.qsys OTHER PATH ../protobuf-serializer/raw_data_out_index.qsys
add_fileset_file out_fifo.qsys OTHER PATH ../protobuf-serializer/out_fifo.qsys
add_fileset_file fsm_0.v VERILOG PATH ../protobuf-serializer/fsm_0.v
add_fileset_file fsm_1.v VERILOG PATH ../protobuf-serializer/fsm_1.v
add_fileset_file fsm_2.v VERILOG PATH ../protobuf-serializer/fsm_2.v
add_fileset_file fsm_3a.v VERILOG PATH ../protobuf-serializer/fsm_3a.v
add_fileset_file fsm_3b.v VERILOG PATH ../protobuf-serializer/fsm_3b.v
add_fileset_file fsm_3.v VERILOG PATH ../protobuf-serializer/fsm_3.v
add_fileset_file fsm_4.v VERILOG PATH ../protobuf-serializer/fsm_4.v


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.compatible "protobuf-serializer"
set_module_assignment embeddedsw.dts.group "hw-accelerator"
set_module_assignment embeddedsw.dts.vendor "att-foundry"


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset_n reset_n Input 1


# 
# connection point s0
# 
add_interface s0 axi4 end
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 readAcceptanceCapability 1
set_interface_property s0 writeAcceptanceCapability 1
set_interface_property s0 combinedAcceptanceCapability 2
set_interface_property s0 readDataReorderingDepth 1
set_interface_property s0 bridgesToMaster ""
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 axs_s0_wstrb wstrb Input 4
add_interface_port s0 axs_s0_wready wready Output 1
add_interface_port s0 axs_s0_wdata wdata Input 32
add_interface_port s0 axs_s0_rvalid rvalid Output 1
add_interface_port s0 axs_s0_rready rready Input 1
add_interface_port s0 axs_s0_rlast rlast Output 1
add_interface_port s0 axs_s0_rid rid Output 4
add_interface_port s0 axs_s0_rdata rdata Output 32
add_interface_port s0 axs_s0_bvalid bvalid Output 1
add_interface_port s0 axs_s0_bready bready Input 1
add_interface_port s0 axs_s0_bid bid Output 4
add_interface_port s0 axs_s0_awsize awsize Input 3
add_interface_port s0 axs_s0_awready awready Output 1
add_interface_port s0 axs_s0_awlen awlen Input 8
add_interface_port s0 axs_s0_awid awid Input 4
add_interface_port s0 axs_s0_awburst awburst Input 2
add_interface_port s0 axs_s0_awaddr awaddr Input 16
add_interface_port s0 axs_s0_arvalid arvalid Input 1
add_interface_port s0 axs_s0_arsize arsize Input 3
add_interface_port s0 axs_s0_arready arready Output 1
add_interface_port s0 axs_s0_arlen arlen Input 8
add_interface_port s0 axs_s0_arid arid Input 4
add_interface_port s0 axs_s0_arburst arburst Input 2
add_interface_port s0 axs_s0_araddr araddr Input 16
add_interface_port s0 axs_s0_wvalid wvalid Input 1
add_interface_port s0 axs_s0_awvalid awvalid Input 1

