// out_fifo.v

// Generated using ACDS version 16.0 211

`timescale 1 ps / 1 ps
module out_fifo (
		input  wire [7:0]  data,  //  fifo_input.datain
		input  wire        wrreq, //            .wrreq
		input  wire        rdreq, //            .rdreq
		input  wire        clock, //            .clk
		output wire [7:0]  q,     // fifo_output.dataout
		output wire [11:0] usedw, //            .usedw
		output wire        full,  //            .full
		output wire        empty  //            .empty
	);

	out_fifo_fifo_160_rvmcgly fifo_0 (
		.data  (data),  //  fifo_input.datain
		.wrreq (wrreq), //            .wrreq
		.rdreq (rdreq), //            .rdreq
		.clock (clock), //            .clk
		.q     (q),     // fifo_output.dataout
		.usedw (usedw), //            .usedw
		.full  (full),  //            .full
		.empty (empty)  //            .empty
	);

endmodule
