config alt_sld_fab_alt_sld_fab_160_gxkkkuy_cfg;
		design alt_sld_fab_alt_sld_fab_160_gxkkkuy;
		instance alt_sld_fab_alt_sld_fab_160_gxkkkuy.presplit use alt_sld_fab_altera_super_splitter_160.alt_sld_fab_altera_super_splitter_160_wbzwvki;
		instance alt_sld_fab_alt_sld_fab_160_gxkkkuy.splitter use alt_sld_fab_altera_sld_splitter_160.alt_sld_fab_altera_sld_splitter_160_ni2nzrq;
		instance alt_sld_fab_alt_sld_fab_160_gxkkkuy.sldfabric use alt_sld_fab_altera_sld_jtag_hub_160.alt_sld_fab_altera_sld_jtag_hub_160_tvwc4fy;
		instance alt_sld_fab_alt_sld_fab_160_gxkkkuy.ident use alt_sld_fab_altera_connection_identification_hub_160.alt_sld_fab_altera_connection_identification_hub_160_7vgsxyi;
endconfig

