config alt_sld_fab_alt_sld_fab_160_bv3idga_cfg;
		design alt_sld_fab_alt_sld_fab_160_bv3idga;
		instance alt_sld_fab_alt_sld_fab_160_bv3idga.presplit use alt_sld_fab_altera_super_splitter_160.alt_sld_fab_altera_super_splitter_160_wbzwvki;
		instance alt_sld_fab_alt_sld_fab_160_bv3idga.splitter use alt_sld_fab_altera_sld_splitter_160.alt_sld_fab_altera_sld_splitter_160_ni2nzrq;
		instance alt_sld_fab_alt_sld_fab_160_bv3idga.sldfabric use alt_sld_fab_altera_sld_jtag_hub_160.alt_sld_fab_altera_sld_jtag_hub_160_tvwc4fy;
		instance alt_sld_fab_alt_sld_fab_160_bv3idga.ident use alt_sld_fab_altera_connection_identification_hub_160.alt_sld_fab_altera_connection_identification_hub_160_3u2qwja;
endconfig

