// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: varint.proto

#ifndef PROTOBUF_varint_2eproto__INCLUDED
#define PROTOBUF_varint_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace test {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_varint_2eproto();
void protobuf_AssignDesc_varint_2eproto();
void protobuf_ShutdownFile_varint_2eproto();

class Varint32;
class Varint32Array;
class Varint64;
class Varint64Array;

// ===================================================================

class Varint32 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:test.Varint32) */ {
 public:
  Varint32();
  virtual ~Varint32();

  Varint32(const Varint32& from);

  inline Varint32& operator=(const Varint32& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Varint32& default_instance();

  void Swap(Varint32* other);

  // implements Message ----------------------------------------------

  inline Varint32* New() const { return New(NULL); }

  Varint32* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Varint32& from);
  void MergeFrom(const Varint32& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Varint32* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 myInt32 = 1;
  void clear_myint32();
  static const int kMyInt32FieldNumber = 1;
  ::google::protobuf::int32 myint32() const;
  void set_myint32(::google::protobuf::int32 value);

  // optional uint32 myUint32 = 2;
  void clear_myuint32();
  static const int kMyUint32FieldNumber = 2;
  ::google::protobuf::uint32 myuint32() const;
  void set_myuint32(::google::protobuf::uint32 value);

  // optional sint32 mySint32 = 3;
  void clear_mysint32();
  static const int kMySint32FieldNumber = 3;
  ::google::protobuf::int32 mysint32() const;
  void set_mysint32(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:test.Varint32)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 myint32_;
  ::google::protobuf::uint32 myuint32_;
  ::google::protobuf::int32 mysint32_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_varint_2eproto();
  friend void protobuf_AssignDesc_varint_2eproto();
  friend void protobuf_ShutdownFile_varint_2eproto();

  void InitAsDefaultInstance();
  static Varint32* default_instance_;
};
// -------------------------------------------------------------------

class Varint64 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:test.Varint64) */ {
 public:
  Varint64();
  virtual ~Varint64();

  Varint64(const Varint64& from);

  inline Varint64& operator=(const Varint64& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Varint64& default_instance();

  void Swap(Varint64* other);

  // implements Message ----------------------------------------------

  inline Varint64* New() const { return New(NULL); }

  Varint64* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Varint64& from);
  void MergeFrom(const Varint64& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Varint64* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 myInt64 = 1;
  void clear_myint64();
  static const int kMyInt64FieldNumber = 1;
  ::google::protobuf::int64 myint64() const;
  void set_myint64(::google::protobuf::int64 value);

  // optional uint64 myUint64 = 2;
  void clear_myuint64();
  static const int kMyUint64FieldNumber = 2;
  ::google::protobuf::uint64 myuint64() const;
  void set_myuint64(::google::protobuf::uint64 value);

  // optional sint64 mySint64 = 3;
  void clear_mysint64();
  static const int kMySint64FieldNumber = 3;
  ::google::protobuf::int64 mysint64() const;
  void set_mysint64(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:test.Varint64)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 myint64_;
  ::google::protobuf::uint64 myuint64_;
  ::google::protobuf::int64 mysint64_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_varint_2eproto();
  friend void protobuf_AssignDesc_varint_2eproto();
  friend void protobuf_ShutdownFile_varint_2eproto();

  void InitAsDefaultInstance();
  static Varint64* default_instance_;
};
// -------------------------------------------------------------------

class Varint32Array : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:test.Varint32Array) */ {
 public:
  Varint32Array();
  virtual ~Varint32Array();

  Varint32Array(const Varint32Array& from);

  inline Varint32Array& operator=(const Varint32Array& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Varint32Array& default_instance();

  void Swap(Varint32Array* other);

  // implements Message ----------------------------------------------

  inline Varint32Array* New() const { return New(NULL); }

  Varint32Array* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Varint32Array& from);
  void MergeFrom(const Varint32Array& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Varint32Array* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .test.Varint32 varint32 = 1;
  int varint32_size() const;
  void clear_varint32();
  static const int kVarint32FieldNumber = 1;
  const ::test::Varint32& varint32(int index) const;
  ::test::Varint32* mutable_varint32(int index);
  ::test::Varint32* add_varint32();
  ::google::protobuf::RepeatedPtrField< ::test::Varint32 >*
      mutable_varint32();
  const ::google::protobuf::RepeatedPtrField< ::test::Varint32 >&
      varint32() const;

  // @@protoc_insertion_point(class_scope:test.Varint32Array)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::test::Varint32 > varint32_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_varint_2eproto();
  friend void protobuf_AssignDesc_varint_2eproto();
  friend void protobuf_ShutdownFile_varint_2eproto();

  void InitAsDefaultInstance();
  static Varint32Array* default_instance_;
};
// -------------------------------------------------------------------

class Varint64Array : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:test.Varint64Array) */ {
 public:
  Varint64Array();
  virtual ~Varint64Array();

  Varint64Array(const Varint64Array& from);

  inline Varint64Array& operator=(const Varint64Array& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Varint64Array& default_instance();

  void Swap(Varint64Array* other);

  // implements Message ----------------------------------------------

  inline Varint64Array* New() const { return New(NULL); }

  Varint64Array* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Varint64Array& from);
  void MergeFrom(const Varint64Array& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Varint64Array* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .test.Varint64 varint64 = 1;
  int varint64_size() const;
  void clear_varint64();
  static const int kVarint64FieldNumber = 1;
  const ::test::Varint64& varint64(int index) const;
  ::test::Varint64* mutable_varint64(int index);
  ::test::Varint64* add_varint64();
  ::google::protobuf::RepeatedPtrField< ::test::Varint64 >*
      mutable_varint64();
  const ::google::protobuf::RepeatedPtrField< ::test::Varint64 >&
      varint64() const;

  // @@protoc_insertion_point(class_scope:test.Varint64Array)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::test::Varint64 > varint64_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_varint_2eproto();
  friend void protobuf_AssignDesc_varint_2eproto();
  friend void protobuf_ShutdownFile_varint_2eproto();

  void InitAsDefaultInstance();
  static Varint64Array* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Varint32

// optional int32 myInt32 = 1;
inline void Varint32::clear_myint32() {
  myint32_ = 0;
}
inline ::google::protobuf::int32 Varint32::myint32() const {
  // @@protoc_insertion_point(field_get:test.Varint32.myInt32)
  return myint32_;
}
inline void Varint32::set_myint32(::google::protobuf::int32 value) {
  
  myint32_ = value;
  // @@protoc_insertion_point(field_set:test.Varint32.myInt32)
}

// optional uint32 myUint32 = 2;
inline void Varint32::clear_myuint32() {
  myuint32_ = 0u;
}
inline ::google::protobuf::uint32 Varint32::myuint32() const {
  // @@protoc_insertion_point(field_get:test.Varint32.myUint32)
  return myuint32_;
}
inline void Varint32::set_myuint32(::google::protobuf::uint32 value) {
  
  myuint32_ = value;
  // @@protoc_insertion_point(field_set:test.Varint32.myUint32)
}

// optional sint32 mySint32 = 3;
inline void Varint32::clear_mysint32() {
  mysint32_ = 0;
}
inline ::google::protobuf::int32 Varint32::mysint32() const {
  // @@protoc_insertion_point(field_get:test.Varint32.mySint32)
  return mysint32_;
}
inline void Varint32::set_mysint32(::google::protobuf::int32 value) {
  
  mysint32_ = value;
  // @@protoc_insertion_point(field_set:test.Varint32.mySint32)
}

// -------------------------------------------------------------------

// Varint64

// optional int64 myInt64 = 1;
inline void Varint64::clear_myint64() {
  myint64_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Varint64::myint64() const {
  // @@protoc_insertion_point(field_get:test.Varint64.myInt64)
  return myint64_;
}
inline void Varint64::set_myint64(::google::protobuf::int64 value) {
  
  myint64_ = value;
  // @@protoc_insertion_point(field_set:test.Varint64.myInt64)
}

// optional uint64 myUint64 = 2;
inline void Varint64::clear_myuint64() {
  myuint64_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Varint64::myuint64() const {
  // @@protoc_insertion_point(field_get:test.Varint64.myUint64)
  return myuint64_;
}
inline void Varint64::set_myuint64(::google::protobuf::uint64 value) {
  
  myuint64_ = value;
  // @@protoc_insertion_point(field_set:test.Varint64.myUint64)
}

// optional sint64 mySint64 = 3;
inline void Varint64::clear_mysint64() {
  mysint64_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Varint64::mysint64() const {
  // @@protoc_insertion_point(field_get:test.Varint64.mySint64)
  return mysint64_;
}
inline void Varint64::set_mysint64(::google::protobuf::int64 value) {
  
  mysint64_ = value;
  // @@protoc_insertion_point(field_set:test.Varint64.mySint64)
}

// -------------------------------------------------------------------

// Varint32Array

// repeated .test.Varint32 varint32 = 1;
inline int Varint32Array::varint32_size() const {
  return varint32_.size();
}
inline void Varint32Array::clear_varint32() {
  varint32_.Clear();
}
inline const ::test::Varint32& Varint32Array::varint32(int index) const {
  // @@protoc_insertion_point(field_get:test.Varint32Array.varint32)
  return varint32_.Get(index);
}
inline ::test::Varint32* Varint32Array::mutable_varint32(int index) {
  // @@protoc_insertion_point(field_mutable:test.Varint32Array.varint32)
  return varint32_.Mutable(index);
}
inline ::test::Varint32* Varint32Array::add_varint32() {
  // @@protoc_insertion_point(field_add:test.Varint32Array.varint32)
  return varint32_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::test::Varint32 >*
Varint32Array::mutable_varint32() {
  // @@protoc_insertion_point(field_mutable_list:test.Varint32Array.varint32)
  return &varint32_;
}
inline const ::google::protobuf::RepeatedPtrField< ::test::Varint32 >&
Varint32Array::varint32() const {
  // @@protoc_insertion_point(field_list:test.Varint32Array.varint32)
  return varint32_;
}

// -------------------------------------------------------------------

// Varint64Array

// repeated .test.Varint64 varint64 = 1;
inline int Varint64Array::varint64_size() const {
  return varint64_.size();
}
inline void Varint64Array::clear_varint64() {
  varint64_.Clear();
}
inline const ::test::Varint64& Varint64Array::varint64(int index) const {
  // @@protoc_insertion_point(field_get:test.Varint64Array.varint64)
  return varint64_.Get(index);
}
inline ::test::Varint64* Varint64Array::mutable_varint64(int index) {
  // @@protoc_insertion_point(field_mutable:test.Varint64Array.varint64)
  return varint64_.Mutable(index);
}
inline ::test::Varint64* Varint64Array::add_varint64() {
  // @@protoc_insertion_point(field_add:test.Varint64Array.varint64)
  return varint64_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::test::Varint64 >*
Varint64Array::mutable_varint64() {
  // @@protoc_insertion_point(field_mutable_list:test.Varint64Array.varint64)
  return &varint64_;
}
inline const ::google::protobuf::RepeatedPtrField< ::test::Varint64 >&
Varint64Array::varint64() const {
  // @@protoc_insertion_point(field_list:test.Varint64Array.varint64)
  return varint64_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace test

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_varint_2eproto__INCLUDED
