config alt_sld_fab_alt_sld_fab_161_jsfgeea_cfg;
		design alt_sld_fab_alt_sld_fab_161_jsfgeea;
		instance alt_sld_fab_alt_sld_fab_161_jsfgeea.presplit use alt_sld_fab_altera_super_splitter_161.alt_sld_fab_altera_super_splitter_161_vumttgi;
		instance alt_sld_fab_alt_sld_fab_161_jsfgeea.splitter use alt_sld_fab_altera_sld_splitter_161.alt_sld_fab_altera_sld_splitter_161_agqapvy;
		instance alt_sld_fab_alt_sld_fab_161_jsfgeea.sldfabric use alt_sld_fab_altera_sld_jtag_hub_161.alt_sld_fab_altera_sld_jtag_hub_161_wbfqiva;
		instance alt_sld_fab_alt_sld_fab_161_jsfgeea.ident use alt_sld_fab_altera_connection_identification_hub_161.alt_sld_fab_altera_connection_identification_hub_161_kzyodwq;
endconfig

