config alt_sld_fab_alt_sld_fab_160_r7z4mxy_cfg;
		design alt_sld_fab_alt_sld_fab_160_r7z4mxy;
		instance alt_sld_fab_alt_sld_fab_160_r7z4mxy.presplit use alt_sld_fab_altera_super_splitter_160.alt_sld_fab_altera_super_splitter_160_wbzwvki;
		instance alt_sld_fab_alt_sld_fab_160_r7z4mxy.splitter use alt_sld_fab_altera_sld_splitter_160.alt_sld_fab_altera_sld_splitter_160_ni2nzrq;
		instance alt_sld_fab_alt_sld_fab_160_r7z4mxy.sldfabric use alt_sld_fab_altera_sld_jtag_hub_160.alt_sld_fab_altera_sld_jtag_hub_160_tvwc4fy;
		instance alt_sld_fab_alt_sld_fab_160_r7z4mxy.ident use alt_sld_fab_altera_connection_identification_hub_160.alt_sld_fab_altera_connection_identification_hub_160_uvob2lq;
endconfig

