// ghrd_10as066n2_altera_arria10_hps_161_wdommvq.v

// This file was auto-generated from altera_hps_arria10_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module ghrd_10as066n2_altera_arria10_hps_161_wdommvq #(
		parameter F2S_Width = 6,
		parameter S2F_Width = 4
	) (
		output wire          h2f_rst_n,                 //           h2f_reset.reset_n
		input  wire          f2h_cold_rst_req_n,        //  f2h_cold_reset_req.reset_n
		input  wire          f2h_dbg_rst_req_n,         // f2h_debug_reset_req.reset_n
		input  wire          f2h_warm_rst_req_n,        //  f2h_warm_reset_req.reset_n
		input  wire [27:0]   f2h_stm_hwevents,          //   f2h_stm_hw_events.stm_hwevents
		input  wire [4095:0] emif_emif_to_hps,          //                emif.emif_to_hps
		output wire [4095:0] emif_hps_to_emif,          //                    .hps_to_emif
		input  wire          emif_emif_to_gp,           //                    .emif_to_gp
		output wire [1:0]    emif_gp_to_emif,           //                    .gp_to_emif
		input  wire          f2h_axi_clk,               //       f2h_axi_clock.clk
		input  wire          f2h_axi_rst,               //       f2h_axi_reset.reset_n
		input  wire [3:0]    f2h_AWID,                  //       f2h_axi_slave.awid
		input  wire [31:0]   f2h_AWADDR,                //                    .awaddr
		input  wire [3:0]    f2h_AWLEN,                 //                    .awlen
		input  wire [2:0]    f2h_AWSIZE,                //                    .awsize
		input  wire [1:0]    f2h_AWBURST,               //                    .awburst
		input  wire [1:0]    f2h_AWLOCK,                //                    .awlock
		input  wire [3:0]    f2h_AWCACHE,               //                    .awcache
		input  wire [2:0]    f2h_AWPROT,                //                    .awprot
		input  wire          f2h_AWVALID,               //                    .awvalid
		output wire          f2h_AWREADY,               //                    .awready
		input  wire [4:0]    f2h_AWUSER,                //                    .awuser
		input  wire [3:0]    f2h_WID,                   //                    .wid
		input  wire [127:0]  f2h_WDATA,                 //                    .wdata
		input  wire [15:0]   f2h_WSTRB,                 //                    .wstrb
		input  wire          f2h_WLAST,                 //                    .wlast
		input  wire          f2h_WVALID,                //                    .wvalid
		output wire          f2h_WREADY,                //                    .wready
		output wire [3:0]    f2h_BID,                   //                    .bid
		output wire [1:0]    f2h_BRESP,                 //                    .bresp
		output wire          f2h_BVALID,                //                    .bvalid
		input  wire          f2h_BREADY,                //                    .bready
		input  wire [3:0]    f2h_ARID,                  //                    .arid
		input  wire [31:0]   f2h_ARADDR,                //                    .araddr
		input  wire [3:0]    f2h_ARLEN,                 //                    .arlen
		input  wire [2:0]    f2h_ARSIZE,                //                    .arsize
		input  wire [1:0]    f2h_ARBURST,               //                    .arburst
		input  wire [1:0]    f2h_ARLOCK,                //                    .arlock
		input  wire [3:0]    f2h_ARCACHE,               //                    .arcache
		input  wire [2:0]    f2h_ARPROT,                //                    .arprot
		input  wire          f2h_ARVALID,               //                    .arvalid
		output wire          f2h_ARREADY,               //                    .arready
		input  wire [4:0]    f2h_ARUSER,                //                    .aruser
		output wire [3:0]    f2h_RID,                   //                    .rid
		output wire [127:0]  f2h_RDATA,                 //                    .rdata
		output wire [1:0]    f2h_RRESP,                 //                    .rresp
		output wire          f2h_RLAST,                 //                    .rlast
		output wire          f2h_RVALID,                //                    .rvalid
		input  wire          f2h_RREADY,                //                    .rready
		input  wire          h2f_lw_axi_clk,            //    h2f_lw_axi_clock.clk
		input  wire          h2f_lw_axi_rst,            //    h2f_lw_axi_reset.reset_n
		output wire [3:0]    h2f_lw_AWID,               //   h2f_lw_axi_master.awid
		output wire [20:0]   h2f_lw_AWADDR,             //                    .awaddr
		output wire [3:0]    h2f_lw_AWLEN,              //                    .awlen
		output wire [2:0]    h2f_lw_AWSIZE,             //                    .awsize
		output wire [1:0]    h2f_lw_AWBURST,            //                    .awburst
		output wire [1:0]    h2f_lw_AWLOCK,             //                    .awlock
		output wire [3:0]    h2f_lw_AWCACHE,            //                    .awcache
		output wire [2:0]    h2f_lw_AWPROT,             //                    .awprot
		output wire          h2f_lw_AWVALID,            //                    .awvalid
		input  wire          h2f_lw_AWREADY,            //                    .awready
		output wire [4:0]    h2f_lw_AWUSER,             //                    .awuser
		output wire [3:0]    h2f_lw_WID,                //                    .wid
		output wire [31:0]   h2f_lw_WDATA,              //                    .wdata
		output wire [3:0]    h2f_lw_WSTRB,              //                    .wstrb
		output wire          h2f_lw_WLAST,              //                    .wlast
		output wire          h2f_lw_WVALID,             //                    .wvalid
		input  wire          h2f_lw_WREADY,             //                    .wready
		input  wire [3:0]    h2f_lw_BID,                //                    .bid
		input  wire [1:0]    h2f_lw_BRESP,              //                    .bresp
		input  wire          h2f_lw_BVALID,             //                    .bvalid
		output wire          h2f_lw_BREADY,             //                    .bready
		output wire [3:0]    h2f_lw_ARID,               //                    .arid
		output wire [20:0]   h2f_lw_ARADDR,             //                    .araddr
		output wire [3:0]    h2f_lw_ARLEN,              //                    .arlen
		output wire [2:0]    h2f_lw_ARSIZE,             //                    .arsize
		output wire [1:0]    h2f_lw_ARBURST,            //                    .arburst
		output wire [1:0]    h2f_lw_ARLOCK,             //                    .arlock
		output wire [3:0]    h2f_lw_ARCACHE,            //                    .arcache
		output wire [2:0]    h2f_lw_ARPROT,             //                    .arprot
		output wire          h2f_lw_ARVALID,            //                    .arvalid
		input  wire          h2f_lw_ARREADY,            //                    .arready
		output wire [4:0]    h2f_lw_ARUSER,             //                    .aruser
		input  wire [3:0]    h2f_lw_RID,                //                    .rid
		input  wire [31:0]   h2f_lw_RDATA,              //                    .rdata
		input  wire [1:0]    h2f_lw_RRESP,              //                    .rresp
		input  wire          h2f_lw_RLAST,              //                    .rlast
		input  wire          h2f_lw_RVALID,             //                    .rvalid
		output wire          h2f_lw_RREADY,             //                    .rready
		input  wire          h2f_axi_clk,               //       h2f_axi_clock.clk
		input  wire          h2f_axi_rst,               //       h2f_axi_reset.reset_n
		output wire [3:0]    h2f_AWID,                  //      h2f_axi_master.awid
		output wire [31:0]   h2f_AWADDR,                //                    .awaddr
		output wire [3:0]    h2f_AWLEN,                 //                    .awlen
		output wire [2:0]    h2f_AWSIZE,                //                    .awsize
		output wire [1:0]    h2f_AWBURST,               //                    .awburst
		output wire [1:0]    h2f_AWLOCK,                //                    .awlock
		output wire [3:0]    h2f_AWCACHE,               //                    .awcache
		output wire [2:0]    h2f_AWPROT,                //                    .awprot
		output wire          h2f_AWVALID,               //                    .awvalid
		input  wire          h2f_AWREADY,               //                    .awready
		output wire [4:0]    h2f_AWUSER,                //                    .awuser
		output wire [3:0]    h2f_WID,                   //                    .wid
		output wire [31:0]   h2f_WDATA,                 //                    .wdata
		output wire [3:0]    h2f_WSTRB,                 //                    .wstrb
		output wire          h2f_WLAST,                 //                    .wlast
		output wire          h2f_WVALID,                //                    .wvalid
		input  wire          h2f_WREADY,                //                    .wready
		input  wire [3:0]    h2f_BID,                   //                    .bid
		input  wire [1:0]    h2f_BRESP,                 //                    .bresp
		input  wire          h2f_BVALID,                //                    .bvalid
		output wire          h2f_BREADY,                //                    .bready
		output wire [3:0]    h2f_ARID,                  //                    .arid
		output wire [31:0]   h2f_ARADDR,                //                    .araddr
		output wire [3:0]    h2f_ARLEN,                 //                    .arlen
		output wire [2:0]    h2f_ARSIZE,                //                    .arsize
		output wire [1:0]    h2f_ARBURST,               //                    .arburst
		output wire [1:0]    h2f_ARLOCK,                //                    .arlock
		output wire [3:0]    h2f_ARCACHE,               //                    .arcache
		output wire [2:0]    h2f_ARPROT,                //                    .arprot
		output wire          h2f_ARVALID,               //                    .arvalid
		input  wire          h2f_ARREADY,               //                    .arready
		output wire [4:0]    h2f_ARUSER,                //                    .aruser
		input  wire [3:0]    h2f_RID,                   //                    .rid
		input  wire [31:0]   h2f_RDATA,                 //                    .rdata
		input  wire [1:0]    h2f_RRESP,                 //                    .rresp
		input  wire          h2f_RLAST,                 //                    .rlast
		input  wire          h2f_RVALID,                //                    .rvalid
		output wire          h2f_RREADY,                //                    .rready
		input  wire          f2sdram0_clk,              //      f2sdram0_clock.clk
		input  wire          f2s_sdram0_rst,            //      f2sdram0_reset.reset_n
		input  wire [31:0]   f2sdram0_ARADDR,           //       f2sdram0_data.araddr
		input  wire [1:0]    f2sdram0_ARBURST,          //                    .arburst
		input  wire [3:0]    f2sdram0_ARCACHE,          //                    .arcache
		input  wire [3:0]    f2sdram0_ARID,             //                    .arid
		input  wire [3:0]    f2sdram0_ARLEN,            //                    .arlen
		input  wire [1:0]    f2sdram0_ARLOCK,           //                    .arlock
		input  wire [2:0]    f2sdram0_ARPROT,           //                    .arprot
		output wire          f2sdram0_ARREADY,          //                    .arready
		input  wire [2:0]    f2sdram0_ARSIZE,           //                    .arsize
		input  wire [4:0]    f2sdram0_ARUSER,           //                    .aruser
		input  wire          f2sdram0_ARVALID,          //                    .arvalid
		input  wire [31:0]   f2sdram0_AWADDR,           //                    .awaddr
		input  wire [1:0]    f2sdram0_AWBURST,          //                    .awburst
		input  wire [3:0]    f2sdram0_AWCACHE,          //                    .awcache
		input  wire [3:0]    f2sdram0_AWID,             //                    .awid
		input  wire [3:0]    f2sdram0_AWLEN,            //                    .awlen
		input  wire [1:0]    f2sdram0_AWLOCK,           //                    .awlock
		input  wire [2:0]    f2sdram0_AWPROT,           //                    .awprot
		output wire          f2sdram0_AWREADY,          //                    .awready
		input  wire [2:0]    f2sdram0_AWSIZE,           //                    .awsize
		input  wire [4:0]    f2sdram0_AWUSER,           //                    .awuser
		input  wire          f2sdram0_AWVALID,          //                    .awvalid
		input  wire [127:0]  f2sdram0_WDATA,            //                    .wdata
		input  wire [3:0]    f2sdram0_WID,              //                    .wid
		input  wire          f2sdram0_WLAST,            //                    .wlast
		output wire          f2sdram0_WREADY,           //                    .wready
		input  wire [15:0]   f2sdram0_WSTRB,            //                    .wstrb
		input  wire          f2sdram0_WVALID,           //                    .wvalid
		output wire [3:0]    f2sdram0_BID,              //                    .bid
		input  wire          f2sdram0_BREADY,           //                    .bready
		output wire [1:0]    f2sdram0_BRESP,            //                    .bresp
		output wire          f2sdram0_BVALID,           //                    .bvalid
		output wire [127:0]  f2sdram0_RDATA,            //                    .rdata
		output wire [3:0]    f2sdram0_RID,              //                    .rid
		output wire          f2sdram0_RLAST,            //                    .rlast
		input  wire          f2sdram0_RREADY,           //                    .rready
		output wire [1:0]    f2sdram0_RRESP,            //                    .rresp
		output wire          f2sdram0_RVALID,           //                    .rvalid
		input  wire          f2sdram2_clk,              //      f2sdram2_clock.clk
		input  wire          f2s_sdram2_rst,            //      f2sdram2_reset.reset_n
		input  wire [31:0]   f2sdram2_ARADDR,           //       f2sdram2_data.araddr
		input  wire [1:0]    f2sdram2_ARBURST,          //                    .arburst
		input  wire [3:0]    f2sdram2_ARCACHE,          //                    .arcache
		input  wire [3:0]    f2sdram2_ARID,             //                    .arid
		input  wire [3:0]    f2sdram2_ARLEN,            //                    .arlen
		input  wire [1:0]    f2sdram2_ARLOCK,           //                    .arlock
		input  wire [2:0]    f2sdram2_ARPROT,           //                    .arprot
		output wire          f2sdram2_ARREADY,          //                    .arready
		input  wire [2:0]    f2sdram2_ARSIZE,           //                    .arsize
		input  wire [4:0]    f2sdram2_ARUSER,           //                    .aruser
		input  wire          f2sdram2_ARVALID,          //                    .arvalid
		input  wire [31:0]   f2sdram2_AWADDR,           //                    .awaddr
		input  wire [1:0]    f2sdram2_AWBURST,          //                    .awburst
		input  wire [3:0]    f2sdram2_AWCACHE,          //                    .awcache
		input  wire [3:0]    f2sdram2_AWID,             //                    .awid
		input  wire [3:0]    f2sdram2_AWLEN,            //                    .awlen
		input  wire [1:0]    f2sdram2_AWLOCK,           //                    .awlock
		input  wire [2:0]    f2sdram2_AWPROT,           //                    .awprot
		output wire          f2sdram2_AWREADY,          //                    .awready
		input  wire [2:0]    f2sdram2_AWSIZE,           //                    .awsize
		input  wire [4:0]    f2sdram2_AWUSER,           //                    .awuser
		input  wire          f2sdram2_AWVALID,          //                    .awvalid
		input  wire [127:0]  f2sdram2_WDATA,            //                    .wdata
		input  wire [3:0]    f2sdram2_WID,              //                    .wid
		input  wire          f2sdram2_WLAST,            //                    .wlast
		output wire          f2sdram2_WREADY,           //                    .wready
		input  wire [15:0]   f2sdram2_WSTRB,            //                    .wstrb
		input  wire          f2sdram2_WVALID,           //                    .wvalid
		output wire [3:0]    f2sdram2_BID,              //                    .bid
		input  wire          f2sdram2_BREADY,           //                    .bready
		output wire [1:0]    f2sdram2_BRESP,            //                    .bresp
		output wire          f2sdram2_BVALID,           //                    .bvalid
		output wire [127:0]  f2sdram2_RDATA,            //                    .rdata
		output wire [3:0]    f2sdram2_RID,              //                    .rid
		output wire          f2sdram2_RLAST,            //                    .rlast
		input  wire          f2sdram2_RREADY,           //                    .rready
		output wire [1:0]    f2sdram2_RRESP,            //                    .rresp
		output wire          f2sdram2_RVALID,           //                    .rvalid
		input  wire [31:0]   f2h_irq_p0,                //            f2h_irq0.irq
		input  wire [31:0]   f2h_irq_p1,                //            f2h_irq1.irq
		output wire          hps_io_phery_emac0_TX_CLK, //              hps_io.hps_io_phery_emac0_TX_CLK
		output wire          hps_io_phery_emac0_TXD0,   //                    .hps_io_phery_emac0_TXD0
		output wire          hps_io_phery_emac0_TXD1,   //                    .hps_io_phery_emac0_TXD1
		output wire          hps_io_phery_emac0_TXD2,   //                    .hps_io_phery_emac0_TXD2
		output wire          hps_io_phery_emac0_TXD3,   //                    .hps_io_phery_emac0_TXD3
		input  wire          hps_io_phery_emac0_RX_CTL, //                    .hps_io_phery_emac0_RX_CTL
		output wire          hps_io_phery_emac0_TX_CTL, //                    .hps_io_phery_emac0_TX_CTL
		input  wire          hps_io_phery_emac0_RX_CLK, //                    .hps_io_phery_emac0_RX_CLK
		input  wire          hps_io_phery_emac0_RXD0,   //                    .hps_io_phery_emac0_RXD0
		input  wire          hps_io_phery_emac0_RXD1,   //                    .hps_io_phery_emac0_RXD1
		input  wire          hps_io_phery_emac0_RXD2,   //                    .hps_io_phery_emac0_RXD2
		input  wire          hps_io_phery_emac0_RXD3,   //                    .hps_io_phery_emac0_RXD3
		inout  wire          hps_io_phery_emac0_MDIO,   //                    .hps_io_phery_emac0_MDIO
		output wire          hps_io_phery_emac0_MDC,    //                    .hps_io_phery_emac0_MDC
		inout  wire          hps_io_phery_sdmmc_CMD,    //                    .hps_io_phery_sdmmc_CMD
		inout  wire          hps_io_phery_sdmmc_D0,     //                    .hps_io_phery_sdmmc_D0
		inout  wire          hps_io_phery_sdmmc_D1,     //                    .hps_io_phery_sdmmc_D1
		inout  wire          hps_io_phery_sdmmc_D2,     //                    .hps_io_phery_sdmmc_D2
		inout  wire          hps_io_phery_sdmmc_D3,     //                    .hps_io_phery_sdmmc_D3
		inout  wire          hps_io_phery_sdmmc_D4,     //                    .hps_io_phery_sdmmc_D4
		inout  wire          hps_io_phery_sdmmc_D5,     //                    .hps_io_phery_sdmmc_D5
		inout  wire          hps_io_phery_sdmmc_D6,     //                    .hps_io_phery_sdmmc_D6
		inout  wire          hps_io_phery_sdmmc_D7,     //                    .hps_io_phery_sdmmc_D7
		output wire          hps_io_phery_sdmmc_CCLK,   //                    .hps_io_phery_sdmmc_CCLK
		inout  wire          hps_io_phery_usb0_DATA0,   //                    .hps_io_phery_usb0_DATA0
		inout  wire          hps_io_phery_usb0_DATA1,   //                    .hps_io_phery_usb0_DATA1
		inout  wire          hps_io_phery_usb0_DATA2,   //                    .hps_io_phery_usb0_DATA2
		inout  wire          hps_io_phery_usb0_DATA3,   //                    .hps_io_phery_usb0_DATA3
		inout  wire          hps_io_phery_usb0_DATA4,   //                    .hps_io_phery_usb0_DATA4
		inout  wire          hps_io_phery_usb0_DATA5,   //                    .hps_io_phery_usb0_DATA5
		inout  wire          hps_io_phery_usb0_DATA6,   //                    .hps_io_phery_usb0_DATA6
		inout  wire          hps_io_phery_usb0_DATA7,   //                    .hps_io_phery_usb0_DATA7
		input  wire          hps_io_phery_usb0_CLK,     //                    .hps_io_phery_usb0_CLK
		output wire          hps_io_phery_usb0_STP,     //                    .hps_io_phery_usb0_STP
		input  wire          hps_io_phery_usb0_DIR,     //                    .hps_io_phery_usb0_DIR
		input  wire          hps_io_phery_usb0_NXT,     //                    .hps_io_phery_usb0_NXT
		output wire          hps_io_phery_spim1_CLK,    //                    .hps_io_phery_spim1_CLK
		output wire          hps_io_phery_spim1_MOSI,   //                    .hps_io_phery_spim1_MOSI
		input  wire          hps_io_phery_spim1_MISO,   //                    .hps_io_phery_spim1_MISO
		output wire          hps_io_phery_spim1_SS0_N,  //                    .hps_io_phery_spim1_SS0_N
		output wire          hps_io_phery_spim1_SS1_N,  //                    .hps_io_phery_spim1_SS1_N
		output wire          hps_io_phery_trace_CLK,    //                    .hps_io_phery_trace_CLK
		output wire          hps_io_phery_trace_D0,     //                    .hps_io_phery_trace_D0
		output wire          hps_io_phery_trace_D1,     //                    .hps_io_phery_trace_D1
		output wire          hps_io_phery_trace_D2,     //                    .hps_io_phery_trace_D2
		output wire          hps_io_phery_trace_D3,     //                    .hps_io_phery_trace_D3
		input  wire          hps_io_phery_uart1_RX,     //                    .hps_io_phery_uart1_RX
		output wire          hps_io_phery_uart1_TX,     //                    .hps_io_phery_uart1_TX
		inout  wire          hps_io_phery_i2c1_SDA,     //                    .hps_io_phery_i2c1_SDA
		inout  wire          hps_io_phery_i2c1_SCL,     //                    .hps_io_phery_i2c1_SCL
		inout  wire          hps_io_gpio_gpio1_io5,     //                    .hps_io_gpio_gpio1_io5
		inout  wire          hps_io_gpio_gpio1_io14,    //                    .hps_io_gpio_gpio1_io14
		inout  wire          hps_io_gpio_gpio1_io16,    //                    .hps_io_gpio_gpio1_io16
		inout  wire          hps_io_gpio_gpio1_io17     //                    .hps_io_gpio_gpio1_io17
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (F2S_Width != 6)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					f2s_width_check ( .error(1'b1) );
		end
		if (S2F_Width != 4)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					s2f_width_check ( .error(1'b1) );
		end
	endgenerate

	ghrd_10as066n2_altera_arria10_interface_generator_140_h73okey fpga_interfaces (
		.h2f_rst_n          (h2f_rst_n),          //           h2f_reset.reset_n
		.f2h_cold_rst_req_n (f2h_cold_rst_req_n), //  f2h_cold_reset_req.reset_n
		.f2h_dbg_rst_req_n  (f2h_dbg_rst_req_n),  // f2h_debug_reset_req.reset_n
		.f2h_warm_rst_req_n (f2h_warm_rst_req_n), //  f2h_warm_reset_req.reset_n
		.f2h_stm_hwevents   (f2h_stm_hwevents),   //   f2h_stm_hw_events.stm_hwevents
		.emif_emif_to_hps   (emif_emif_to_hps),   //                emif.emif_to_hps
		.emif_hps_to_emif   (emif_hps_to_emif),   //                    .hps_to_emif
		.emif_emif_to_gp    (emif_emif_to_gp),    //                    .emif_to_gp
		.emif_gp_to_emif    (emif_gp_to_emif),    //                    .gp_to_emif
		.f2h_axi_clk        (f2h_axi_clk),        //       f2h_axi_clock.clk
		.f2h_axi_rst        (f2h_axi_rst),        //       f2h_axi_reset.reset_n
		.f2h_AWID           (f2h_AWID),           //       f2h_axi_slave.awid
		.f2h_AWADDR         (f2h_AWADDR),         //                    .awaddr
		.f2h_AWLEN          (f2h_AWLEN),          //                    .awlen
		.f2h_AWSIZE         (f2h_AWSIZE),         //                    .awsize
		.f2h_AWBURST        (f2h_AWBURST),        //                    .awburst
		.f2h_AWLOCK         (f2h_AWLOCK),         //                    .awlock
		.f2h_AWCACHE        (f2h_AWCACHE),        //                    .awcache
		.f2h_AWPROT         (f2h_AWPROT),         //                    .awprot
		.f2h_AWVALID        (f2h_AWVALID),        //                    .awvalid
		.f2h_AWREADY        (f2h_AWREADY),        //                    .awready
		.f2h_AWUSER         (f2h_AWUSER),         //                    .awuser
		.f2h_WID            (f2h_WID),            //                    .wid
		.f2h_WDATA          (f2h_WDATA),          //                    .wdata
		.f2h_WSTRB          (f2h_WSTRB),          //                    .wstrb
		.f2h_WLAST          (f2h_WLAST),          //                    .wlast
		.f2h_WVALID         (f2h_WVALID),         //                    .wvalid
		.f2h_WREADY         (f2h_WREADY),         //                    .wready
		.f2h_BID            (f2h_BID),            //                    .bid
		.f2h_BRESP          (f2h_BRESP),          //                    .bresp
		.f2h_BVALID         (f2h_BVALID),         //                    .bvalid
		.f2h_BREADY         (f2h_BREADY),         //                    .bready
		.f2h_ARID           (f2h_ARID),           //                    .arid
		.f2h_ARADDR         (f2h_ARADDR),         //                    .araddr
		.f2h_ARLEN          (f2h_ARLEN),          //                    .arlen
		.f2h_ARSIZE         (f2h_ARSIZE),         //                    .arsize
		.f2h_ARBURST        (f2h_ARBURST),        //                    .arburst
		.f2h_ARLOCK         (f2h_ARLOCK),         //                    .arlock
		.f2h_ARCACHE        (f2h_ARCACHE),        //                    .arcache
		.f2h_ARPROT         (f2h_ARPROT),         //                    .arprot
		.f2h_ARVALID        (f2h_ARVALID),        //                    .arvalid
		.f2h_ARREADY        (f2h_ARREADY),        //                    .arready
		.f2h_ARUSER         (f2h_ARUSER),         //                    .aruser
		.f2h_RID            (f2h_RID),            //                    .rid
		.f2h_RDATA          (f2h_RDATA),          //                    .rdata
		.f2h_RRESP          (f2h_RRESP),          //                    .rresp
		.f2h_RLAST          (f2h_RLAST),          //                    .rlast
		.f2h_RVALID         (f2h_RVALID),         //                    .rvalid
		.f2h_RREADY         (f2h_RREADY),         //                    .rready
		.h2f_lw_axi_clk     (h2f_lw_axi_clk),     //    h2f_lw_axi_clock.clk
		.h2f_lw_axi_rst     (h2f_lw_axi_rst),     //    h2f_lw_axi_reset.reset_n
		.h2f_lw_AWID        (h2f_lw_AWID),        //   h2f_lw_axi_master.awid
		.h2f_lw_AWADDR      (h2f_lw_AWADDR),      //                    .awaddr
		.h2f_lw_AWLEN       (h2f_lw_AWLEN),       //                    .awlen
		.h2f_lw_AWSIZE      (h2f_lw_AWSIZE),      //                    .awsize
		.h2f_lw_AWBURST     (h2f_lw_AWBURST),     //                    .awburst
		.h2f_lw_AWLOCK      (h2f_lw_AWLOCK),      //                    .awlock
		.h2f_lw_AWCACHE     (h2f_lw_AWCACHE),     //                    .awcache
		.h2f_lw_AWPROT      (h2f_lw_AWPROT),      //                    .awprot
		.h2f_lw_AWVALID     (h2f_lw_AWVALID),     //                    .awvalid
		.h2f_lw_AWREADY     (h2f_lw_AWREADY),     //                    .awready
		.h2f_lw_AWUSER      (h2f_lw_AWUSER),      //                    .awuser
		.h2f_lw_WID         (h2f_lw_WID),         //                    .wid
		.h2f_lw_WDATA       (h2f_lw_WDATA),       //                    .wdata
		.h2f_lw_WSTRB       (h2f_lw_WSTRB),       //                    .wstrb
		.h2f_lw_WLAST       (h2f_lw_WLAST),       //                    .wlast
		.h2f_lw_WVALID      (h2f_lw_WVALID),      //                    .wvalid
		.h2f_lw_WREADY      (h2f_lw_WREADY),      //                    .wready
		.h2f_lw_BID         (h2f_lw_BID),         //                    .bid
		.h2f_lw_BRESP       (h2f_lw_BRESP),       //                    .bresp
		.h2f_lw_BVALID      (h2f_lw_BVALID),      //                    .bvalid
		.h2f_lw_BREADY      (h2f_lw_BREADY),      //                    .bready
		.h2f_lw_ARID        (h2f_lw_ARID),        //                    .arid
		.h2f_lw_ARADDR      (h2f_lw_ARADDR),      //                    .araddr
		.h2f_lw_ARLEN       (h2f_lw_ARLEN),       //                    .arlen
		.h2f_lw_ARSIZE      (h2f_lw_ARSIZE),      //                    .arsize
		.h2f_lw_ARBURST     (h2f_lw_ARBURST),     //                    .arburst
		.h2f_lw_ARLOCK      (h2f_lw_ARLOCK),      //                    .arlock
		.h2f_lw_ARCACHE     (h2f_lw_ARCACHE),     //                    .arcache
		.h2f_lw_ARPROT      (h2f_lw_ARPROT),      //                    .arprot
		.h2f_lw_ARVALID     (h2f_lw_ARVALID),     //                    .arvalid
		.h2f_lw_ARREADY     (h2f_lw_ARREADY),     //                    .arready
		.h2f_lw_ARUSER      (h2f_lw_ARUSER),      //                    .aruser
		.h2f_lw_RID         (h2f_lw_RID),         //                    .rid
		.h2f_lw_RDATA       (h2f_lw_RDATA),       //                    .rdata
		.h2f_lw_RRESP       (h2f_lw_RRESP),       //                    .rresp
		.h2f_lw_RLAST       (h2f_lw_RLAST),       //                    .rlast
		.h2f_lw_RVALID      (h2f_lw_RVALID),      //                    .rvalid
		.h2f_lw_RREADY      (h2f_lw_RREADY),      //                    .rready
		.h2f_axi_clk        (h2f_axi_clk),        //       h2f_axi_clock.clk
		.h2f_axi_rst        (h2f_axi_rst),        //       h2f_axi_reset.reset_n
		.h2f_AWID           (h2f_AWID),           //      h2f_axi_master.awid
		.h2f_AWADDR         (h2f_AWADDR),         //                    .awaddr
		.h2f_AWLEN          (h2f_AWLEN),          //                    .awlen
		.h2f_AWSIZE         (h2f_AWSIZE),         //                    .awsize
		.h2f_AWBURST        (h2f_AWBURST),        //                    .awburst
		.h2f_AWLOCK         (h2f_AWLOCK),         //                    .awlock
		.h2f_AWCACHE        (h2f_AWCACHE),        //                    .awcache
		.h2f_AWPROT         (h2f_AWPROT),         //                    .awprot
		.h2f_AWVALID        (h2f_AWVALID),        //                    .awvalid
		.h2f_AWREADY        (h2f_AWREADY),        //                    .awready
		.h2f_AWUSER         (h2f_AWUSER),         //                    .awuser
		.h2f_WID            (h2f_WID),            //                    .wid
		.h2f_WDATA          (h2f_WDATA),          //                    .wdata
		.h2f_WSTRB          (h2f_WSTRB),          //                    .wstrb
		.h2f_WLAST          (h2f_WLAST),          //                    .wlast
		.h2f_WVALID         (h2f_WVALID),         //                    .wvalid
		.h2f_WREADY         (h2f_WREADY),         //                    .wready
		.h2f_BID            (h2f_BID),            //                    .bid
		.h2f_BRESP          (h2f_BRESP),          //                    .bresp
		.h2f_BVALID         (h2f_BVALID),         //                    .bvalid
		.h2f_BREADY         (h2f_BREADY),         //                    .bready
		.h2f_ARID           (h2f_ARID),           //                    .arid
		.h2f_ARADDR         (h2f_ARADDR),         //                    .araddr
		.h2f_ARLEN          (h2f_ARLEN),          //                    .arlen
		.h2f_ARSIZE         (h2f_ARSIZE),         //                    .arsize
		.h2f_ARBURST        (h2f_ARBURST),        //                    .arburst
		.h2f_ARLOCK         (h2f_ARLOCK),         //                    .arlock
		.h2f_ARCACHE        (h2f_ARCACHE),        //                    .arcache
		.h2f_ARPROT         (h2f_ARPROT),         //                    .arprot
		.h2f_ARVALID        (h2f_ARVALID),        //                    .arvalid
		.h2f_ARREADY        (h2f_ARREADY),        //                    .arready
		.h2f_ARUSER         (h2f_ARUSER),         //                    .aruser
		.h2f_RID            (h2f_RID),            //                    .rid
		.h2f_RDATA          (h2f_RDATA),          //                    .rdata
		.h2f_RRESP          (h2f_RRESP),          //                    .rresp
		.h2f_RLAST          (h2f_RLAST),          //                    .rlast
		.h2f_RVALID         (h2f_RVALID),         //                    .rvalid
		.h2f_RREADY         (h2f_RREADY),         //                    .rready
		.f2sdram0_clk       (f2sdram0_clk),       //      f2sdram0_clock.clk
		.f2s_sdram0_rst     (f2s_sdram0_rst),     //      f2sdram0_reset.reset_n
		.f2sdram0_ARADDR    (f2sdram0_ARADDR),    //       f2sdram0_data.araddr
		.f2sdram0_ARBURST   (f2sdram0_ARBURST),   //                    .arburst
		.f2sdram0_ARCACHE   (f2sdram0_ARCACHE),   //                    .arcache
		.f2sdram0_ARID      (f2sdram0_ARID),      //                    .arid
		.f2sdram0_ARLEN     (f2sdram0_ARLEN),     //                    .arlen
		.f2sdram0_ARLOCK    (f2sdram0_ARLOCK),    //                    .arlock
		.f2sdram0_ARPROT    (f2sdram0_ARPROT),    //                    .arprot
		.f2sdram0_ARREADY   (f2sdram0_ARREADY),   //                    .arready
		.f2sdram0_ARSIZE    (f2sdram0_ARSIZE),    //                    .arsize
		.f2sdram0_ARUSER    (f2sdram0_ARUSER),    //                    .aruser
		.f2sdram0_ARVALID   (f2sdram0_ARVALID),   //                    .arvalid
		.f2sdram0_AWADDR    (f2sdram0_AWADDR),    //                    .awaddr
		.f2sdram0_AWBURST   (f2sdram0_AWBURST),   //                    .awburst
		.f2sdram0_AWCACHE   (f2sdram0_AWCACHE),   //                    .awcache
		.f2sdram0_AWID      (f2sdram0_AWID),      //                    .awid
		.f2sdram0_AWLEN     (f2sdram0_AWLEN),     //                    .awlen
		.f2sdram0_AWLOCK    (f2sdram0_AWLOCK),    //                    .awlock
		.f2sdram0_AWPROT    (f2sdram0_AWPROT),    //                    .awprot
		.f2sdram0_AWREADY   (f2sdram0_AWREADY),   //                    .awready
		.f2sdram0_AWSIZE    (f2sdram0_AWSIZE),    //                    .awsize
		.f2sdram0_AWUSER    (f2sdram0_AWUSER),    //                    .awuser
		.f2sdram0_AWVALID   (f2sdram0_AWVALID),   //                    .awvalid
		.f2sdram0_WDATA     (f2sdram0_WDATA),     //                    .wdata
		.f2sdram0_WID       (f2sdram0_WID),       //                    .wid
		.f2sdram0_WLAST     (f2sdram0_WLAST),     //                    .wlast
		.f2sdram0_WREADY    (f2sdram0_WREADY),    //                    .wready
		.f2sdram0_WSTRB     (f2sdram0_WSTRB),     //                    .wstrb
		.f2sdram0_WVALID    (f2sdram0_WVALID),    //                    .wvalid
		.f2sdram0_BID       (f2sdram0_BID),       //                    .bid
		.f2sdram0_BREADY    (f2sdram0_BREADY),    //                    .bready
		.f2sdram0_BRESP     (f2sdram0_BRESP),     //                    .bresp
		.f2sdram0_BVALID    (f2sdram0_BVALID),    //                    .bvalid
		.f2sdram0_RDATA     (f2sdram0_RDATA),     //                    .rdata
		.f2sdram0_RID       (f2sdram0_RID),       //                    .rid
		.f2sdram0_RLAST     (f2sdram0_RLAST),     //                    .rlast
		.f2sdram0_RREADY    (f2sdram0_RREADY),    //                    .rready
		.f2sdram0_RRESP     (f2sdram0_RRESP),     //                    .rresp
		.f2sdram0_RVALID    (f2sdram0_RVALID),    //                    .rvalid
		.f2sdram2_clk       (f2sdram2_clk),       //      f2sdram2_clock.clk
		.f2s_sdram2_rst     (f2s_sdram2_rst),     //      f2sdram2_reset.reset_n
		.f2sdram2_ARADDR    (f2sdram2_ARADDR),    //       f2sdram2_data.araddr
		.f2sdram2_ARBURST   (f2sdram2_ARBURST),   //                    .arburst
		.f2sdram2_ARCACHE   (f2sdram2_ARCACHE),   //                    .arcache
		.f2sdram2_ARID      (f2sdram2_ARID),      //                    .arid
		.f2sdram2_ARLEN     (f2sdram2_ARLEN),     //                    .arlen
		.f2sdram2_ARLOCK    (f2sdram2_ARLOCK),    //                    .arlock
		.f2sdram2_ARPROT    (f2sdram2_ARPROT),    //                    .arprot
		.f2sdram2_ARREADY   (f2sdram2_ARREADY),   //                    .arready
		.f2sdram2_ARSIZE    (f2sdram2_ARSIZE),    //                    .arsize
		.f2sdram2_ARUSER    (f2sdram2_ARUSER),    //                    .aruser
		.f2sdram2_ARVALID   (f2sdram2_ARVALID),   //                    .arvalid
		.f2sdram2_AWADDR    (f2sdram2_AWADDR),    //                    .awaddr
		.f2sdram2_AWBURST   (f2sdram2_AWBURST),   //                    .awburst
		.f2sdram2_AWCACHE   (f2sdram2_AWCACHE),   //                    .awcache
		.f2sdram2_AWID      (f2sdram2_AWID),      //                    .awid
		.f2sdram2_AWLEN     (f2sdram2_AWLEN),     //                    .awlen
		.f2sdram2_AWLOCK    (f2sdram2_AWLOCK),    //                    .awlock
		.f2sdram2_AWPROT    (f2sdram2_AWPROT),    //                    .awprot
		.f2sdram2_AWREADY   (f2sdram2_AWREADY),   //                    .awready
		.f2sdram2_AWSIZE    (f2sdram2_AWSIZE),    //                    .awsize
		.f2sdram2_AWUSER    (f2sdram2_AWUSER),    //                    .awuser
		.f2sdram2_AWVALID   (f2sdram2_AWVALID),   //                    .awvalid
		.f2sdram2_WDATA     (f2sdram2_WDATA),     //                    .wdata
		.f2sdram2_WID       (f2sdram2_WID),       //                    .wid
		.f2sdram2_WLAST     (f2sdram2_WLAST),     //                    .wlast
		.f2sdram2_WREADY    (f2sdram2_WREADY),    //                    .wready
		.f2sdram2_WSTRB     (f2sdram2_WSTRB),     //                    .wstrb
		.f2sdram2_WVALID    (f2sdram2_WVALID),    //                    .wvalid
		.f2sdram2_BID       (f2sdram2_BID),       //                    .bid
		.f2sdram2_BREADY    (f2sdram2_BREADY),    //                    .bready
		.f2sdram2_BRESP     (f2sdram2_BRESP),     //                    .bresp
		.f2sdram2_BVALID    (f2sdram2_BVALID),    //                    .bvalid
		.f2sdram2_RDATA     (f2sdram2_RDATA),     //                    .rdata
		.f2sdram2_RID       (f2sdram2_RID),       //                    .rid
		.f2sdram2_RLAST     (f2sdram2_RLAST),     //                    .rlast
		.f2sdram2_RREADY    (f2sdram2_RREADY),    //                    .rready
		.f2sdram2_RRESP     (f2sdram2_RRESP),     //                    .rresp
		.f2sdram2_RVALID    (f2sdram2_RVALID),    //                    .rvalid
		.f2h_irq_p0         (f2h_irq_p0),         //            f2h_irq0.irq
		.f2h_irq_p1         (f2h_irq_p1)          //            f2h_irq1.irq
	);

	ghrd_10as066n2_altera_arria10_hps_io_161_yhkpgdq hps_io (
		.hps_io_phery_emac0_TX_CLK (hps_io_phery_emac0_TX_CLK), // hps_io.hps_io_phery_emac0_TX_CLK
		.hps_io_phery_emac0_TXD0   (hps_io_phery_emac0_TXD0),   //       .hps_io_phery_emac0_TXD0
		.hps_io_phery_emac0_TXD1   (hps_io_phery_emac0_TXD1),   //       .hps_io_phery_emac0_TXD1
		.hps_io_phery_emac0_TXD2   (hps_io_phery_emac0_TXD2),   //       .hps_io_phery_emac0_TXD2
		.hps_io_phery_emac0_TXD3   (hps_io_phery_emac0_TXD3),   //       .hps_io_phery_emac0_TXD3
		.hps_io_phery_emac0_RX_CTL (hps_io_phery_emac0_RX_CTL), //       .hps_io_phery_emac0_RX_CTL
		.hps_io_phery_emac0_TX_CTL (hps_io_phery_emac0_TX_CTL), //       .hps_io_phery_emac0_TX_CTL
		.hps_io_phery_emac0_RX_CLK (hps_io_phery_emac0_RX_CLK), //       .hps_io_phery_emac0_RX_CLK
		.hps_io_phery_emac0_RXD0   (hps_io_phery_emac0_RXD0),   //       .hps_io_phery_emac0_RXD0
		.hps_io_phery_emac0_RXD1   (hps_io_phery_emac0_RXD1),   //       .hps_io_phery_emac0_RXD1
		.hps_io_phery_emac0_RXD2   (hps_io_phery_emac0_RXD2),   //       .hps_io_phery_emac0_RXD2
		.hps_io_phery_emac0_RXD3   (hps_io_phery_emac0_RXD3),   //       .hps_io_phery_emac0_RXD3
		.hps_io_phery_emac0_MDIO   (hps_io_phery_emac0_MDIO),   //       .hps_io_phery_emac0_MDIO
		.hps_io_phery_emac0_MDC    (hps_io_phery_emac0_MDC),    //       .hps_io_phery_emac0_MDC
		.hps_io_phery_sdmmc_CMD    (hps_io_phery_sdmmc_CMD),    //       .hps_io_phery_sdmmc_CMD
		.hps_io_phery_sdmmc_D0     (hps_io_phery_sdmmc_D0),     //       .hps_io_phery_sdmmc_D0
		.hps_io_phery_sdmmc_D1     (hps_io_phery_sdmmc_D1),     //       .hps_io_phery_sdmmc_D1
		.hps_io_phery_sdmmc_D2     (hps_io_phery_sdmmc_D2),     //       .hps_io_phery_sdmmc_D2
		.hps_io_phery_sdmmc_D3     (hps_io_phery_sdmmc_D3),     //       .hps_io_phery_sdmmc_D3
		.hps_io_phery_sdmmc_D4     (hps_io_phery_sdmmc_D4),     //       .hps_io_phery_sdmmc_D4
		.hps_io_phery_sdmmc_D5     (hps_io_phery_sdmmc_D5),     //       .hps_io_phery_sdmmc_D5
		.hps_io_phery_sdmmc_D6     (hps_io_phery_sdmmc_D6),     //       .hps_io_phery_sdmmc_D6
		.hps_io_phery_sdmmc_D7     (hps_io_phery_sdmmc_D7),     //       .hps_io_phery_sdmmc_D7
		.hps_io_phery_sdmmc_CCLK   (hps_io_phery_sdmmc_CCLK),   //       .hps_io_phery_sdmmc_CCLK
		.hps_io_phery_usb0_DATA0   (hps_io_phery_usb0_DATA0),   //       .hps_io_phery_usb0_DATA0
		.hps_io_phery_usb0_DATA1   (hps_io_phery_usb0_DATA1),   //       .hps_io_phery_usb0_DATA1
		.hps_io_phery_usb0_DATA2   (hps_io_phery_usb0_DATA2),   //       .hps_io_phery_usb0_DATA2
		.hps_io_phery_usb0_DATA3   (hps_io_phery_usb0_DATA3),   //       .hps_io_phery_usb0_DATA3
		.hps_io_phery_usb0_DATA4   (hps_io_phery_usb0_DATA4),   //       .hps_io_phery_usb0_DATA4
		.hps_io_phery_usb0_DATA5   (hps_io_phery_usb0_DATA5),   //       .hps_io_phery_usb0_DATA5
		.hps_io_phery_usb0_DATA6   (hps_io_phery_usb0_DATA6),   //       .hps_io_phery_usb0_DATA6
		.hps_io_phery_usb0_DATA7   (hps_io_phery_usb0_DATA7),   //       .hps_io_phery_usb0_DATA7
		.hps_io_phery_usb0_CLK     (hps_io_phery_usb0_CLK),     //       .hps_io_phery_usb0_CLK
		.hps_io_phery_usb0_STP     (hps_io_phery_usb0_STP),     //       .hps_io_phery_usb0_STP
		.hps_io_phery_usb0_DIR     (hps_io_phery_usb0_DIR),     //       .hps_io_phery_usb0_DIR
		.hps_io_phery_usb0_NXT     (hps_io_phery_usb0_NXT),     //       .hps_io_phery_usb0_NXT
		.hps_io_phery_spim1_CLK    (hps_io_phery_spim1_CLK),    //       .hps_io_phery_spim1_CLK
		.hps_io_phery_spim1_MOSI   (hps_io_phery_spim1_MOSI),   //       .hps_io_phery_spim1_MOSI
		.hps_io_phery_spim1_MISO   (hps_io_phery_spim1_MISO),   //       .hps_io_phery_spim1_MISO
		.hps_io_phery_spim1_SS0_N  (hps_io_phery_spim1_SS0_N),  //       .hps_io_phery_spim1_SS0_N
		.hps_io_phery_spim1_SS1_N  (hps_io_phery_spim1_SS1_N),  //       .hps_io_phery_spim1_SS1_N
		.hps_io_phery_trace_CLK    (hps_io_phery_trace_CLK),    //       .hps_io_phery_trace_CLK
		.hps_io_phery_trace_D0     (hps_io_phery_trace_D0),     //       .hps_io_phery_trace_D0
		.hps_io_phery_trace_D1     (hps_io_phery_trace_D1),     //       .hps_io_phery_trace_D1
		.hps_io_phery_trace_D2     (hps_io_phery_trace_D2),     //       .hps_io_phery_trace_D2
		.hps_io_phery_trace_D3     (hps_io_phery_trace_D3),     //       .hps_io_phery_trace_D3
		.hps_io_phery_uart1_RX     (hps_io_phery_uart1_RX),     //       .hps_io_phery_uart1_RX
		.hps_io_phery_uart1_TX     (hps_io_phery_uart1_TX),     //       .hps_io_phery_uart1_TX
		.hps_io_phery_i2c1_SDA     (hps_io_phery_i2c1_SDA),     //       .hps_io_phery_i2c1_SDA
		.hps_io_phery_i2c1_SCL     (hps_io_phery_i2c1_SCL),     //       .hps_io_phery_i2c1_SCL
		.hps_io_gpio_gpio1_io5     (hps_io_gpio_gpio1_io5),     //       .hps_io_gpio_gpio1_io5
		.hps_io_gpio_gpio1_io14    (hps_io_gpio_gpio1_io14),    //       .hps_io_gpio_gpio1_io14
		.hps_io_gpio_gpio1_io16    (hps_io_gpio_gpio1_io16),    //       .hps_io_gpio_gpio1_io16
		.hps_io_gpio_gpio1_io17    (hps_io_gpio_gpio1_io17)     //       .hps_io_gpio_gpio1_io17
	);

endmodule
