# (C) 2001-2015 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 14.1
# Tue Jun 24 10:37:19 MYT 2014
# DO NOT MODIFY


# 
# altera_gmii_to_sgmii_adapter "altera_gmii_to_sgmii_adapter" v1.0
# Altera Corporation 2014.06.24.10:37:19
# GMII to SGMII Adapter
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.0


# 
# module altera_gmii_to_sgmii_adapter
# 
set_module_property DESCRIPTION "GMII to SGMII Adapter"
set_module_property NAME altera_gmii_to_sgmii_adapter
set_module_property VERSION 15.2
set_module_property INTERNAL false
set_module_property HIDE_FROM_QUARTUS true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Processors and Peripherals/Hard Processor Components"
set_module_property AUTHOR "Altera Corporation"
set_module_property DISPLAY_NAME "Altera GMII to SGMII Adapter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property supported_device_families {{Arria 10} {Arria V} {Cyclone V}}

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_gmii_to_sgmii_adapter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_gmii_to_sgmii_adapter.v VERILOG PATH altera_gmii_to_sgmii_adapter.v TOP_LEVEL_FILE
add_fileset_file altera_gts_bin_gray.v VERILOG PATH altera_gts_bin_gray.v
add_fileset_file altera_gts_clock_gate.v VERILOG PATH altera_gts_clock_gate.v
add_fileset_file altera_gts_csr.v VERILOG PATH altera_gts_csr.v
add_fileset_file altera_gts_fifomem.v VERILOG PATH altera_gts_fifomem.v
add_fileset_file altera_gts_gray_bin.v VERILOG PATH altera_gts_gray_bin.v
add_fileset_file altera_gts_reset_blk.v VERILOG PATH altera_gts_reset_blk.v
add_fileset_file altera_gts_reset_synchronizer.v VERILOG PATH altera_gts_reset_synchronizer.v
add_fileset_file altera_gts_synchronizer_bundle.v VERILOG PATH altera_gts_synchronizer_bundle.v
add_fileset_file altera_gts_txbuffer.v VERILOG PATH altera_gts_txbuffer.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_gmii_to_sgmii_adapter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_gmii_to_sgmii_adapter.v VERILOG PATH altera_gmii_to_sgmii_adapter.v
add_fileset_file altera_gts_bin_gray.v VERILOG PATH altera_gts_bin_gray.v
add_fileset_file altera_gts_clock_gate.v VERILOG PATH altera_gts_clock_gate.v
add_fileset_file altera_gts_csr.v VERILOG PATH altera_gts_csr.v
add_fileset_file altera_gts_fifomem.v VERILOG PATH altera_gts_fifomem.v
add_fileset_file altera_gts_gray_bin.v VERILOG PATH altera_gts_gray_bin.v
add_fileset_file altera_gts_reset_blk.v VERILOG PATH altera_gts_reset_blk.v
add_fileset_file altera_gts_reset_synchronizer.v VERILOG PATH altera_gts_reset_synchronizer.v
add_fileset_file altera_gts_synchronizer_bundle.v VERILOG PATH altera_gts_synchronizer_bundle.v
add_fileset_file altera_gts_txbuffer.v VERILOG PATH altera_gts_txbuffer.v

#
# link to datasheet of component -- documentation of this component to be updated as part of embedded IP user guide 
#
add_documentation_link {Data Sheet } {http://www.altera.com/literature/ug/ug_embedded_ip.pdf}


# 
# parameters
# 

# 
# display items
# 


# 
# connection point peri_clock
# 
add_interface peri_clock clock end
set_interface_property peri_clock clockRate 0
set_interface_property peri_clock ENABLED true
set_interface_property peri_clock EXPORT_OF ""
set_interface_property peri_clock PORT_NAME_MAP ""
set_interface_property peri_clock CMSIS_SVD_VARIABLES ""
set_interface_property peri_clock SVD_ADDRESS_GROUP ""

add_interface_port peri_clock clk clk Input 1


# 
# connection point peri_reset
# 
add_interface peri_reset reset end
set_interface_property peri_reset associatedClock peri_clock
set_interface_property peri_reset synchronousEdges DEASSERT
set_interface_property peri_reset ENABLED true
set_interface_property peri_reset EXPORT_OF ""
set_interface_property peri_reset PORT_NAME_MAP ""
set_interface_property peri_reset CMSIS_SVD_VARIABLES ""
set_interface_property peri_reset SVD_ADDRESS_GROUP ""

add_interface_port peri_reset rst_n reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock peri_clock
set_interface_property avalon_slave associatedReset peri_reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 1
set_interface_property avalon_slave readWaitStates 0
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave addr address Input 1
add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave writedata writedata Input 32
add_interface_port avalon_slave readdata readdata Output 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point hps_gmii
# 
add_interface hps_gmii conduit end
set_interface_property hps_gmii associatedClock ""
set_interface_property hps_gmii associatedReset ""
set_interface_property hps_gmii ENABLED true
set_interface_property hps_gmii EXPORT_OF ""
set_interface_property hps_gmii PORT_NAME_MAP ""
set_interface_property hps_gmii CMSIS_SVD_VARIABLES ""
set_interface_property hps_gmii SVD_ADDRESS_GROUP ""

add_interface_port hps_gmii mac_tx_clk_o phy_tx_clk_o Input 1
add_interface_port hps_gmii mac_rst_tx_n rst_tx_n Input 1
add_interface_port hps_gmii mac_rst_rx_n rst_rx_n Input 1
add_interface_port hps_gmii mac_txd phy_txd_o Input 8
add_interface_port hps_gmii mac_txen phy_txen_o Input 1
add_interface_port hps_gmii mac_txer phy_txer_o Input 1
add_interface_port hps_gmii mac_speed phy_mac_speed_o Input 2
add_interface_port hps_gmii mac_tx_clk_i phy_tx_clk_i Output 1
add_interface_port hps_gmii mac_rx_clk phy_rx_clk_i Output 1
add_interface_port hps_gmii mac_rxdv phy_rxdv_i Output 1
add_interface_port hps_gmii mac_rxer phy_rxer_i Output 1
add_interface_port hps_gmii mac_rxd phy_rxd_i Output 8
add_interface_port hps_gmii mac_col phy_col_i Output 1
add_interface_port hps_gmii mac_crs phy_crs_i Output 1


# 
# connection point pcs_transmit_reset
# 
add_interface pcs_transmit_reset reset start
set_interface_property pcs_transmit_reset associatedClock ""
set_interface_property pcs_transmit_reset associatedDirectReset ""
set_interface_property pcs_transmit_reset associatedResetSinks ""
set_interface_property pcs_transmit_reset synchronousEdges NONE
set_interface_property pcs_transmit_reset ENABLED true
set_interface_property pcs_transmit_reset EXPORT_OF ""
set_interface_property pcs_transmit_reset PORT_NAME_MAP ""
set_interface_property pcs_transmit_reset CMSIS_SVD_VARIABLES ""
set_interface_property pcs_transmit_reset SVD_ADDRESS_GROUP ""

add_interface_port pcs_transmit_reset pcs_rst_tx reset Output 1


# 
# connection point pcs_receive_reset
# 
add_interface pcs_receive_reset reset start
set_interface_property pcs_receive_reset associatedClock ""
set_interface_property pcs_receive_reset associatedDirectReset ""
set_interface_property pcs_receive_reset associatedResetSinks ""
set_interface_property pcs_receive_reset synchronousEdges NONE
set_interface_property pcs_receive_reset ENABLED true
set_interface_property pcs_receive_reset EXPORT_OF ""
set_interface_property pcs_receive_reset PORT_NAME_MAP ""
set_interface_property pcs_receive_reset CMSIS_SVD_VARIABLES ""
set_interface_property pcs_receive_reset SVD_ADDRESS_GROUP ""

add_interface_port pcs_receive_reset pcs_rst_rx reset Output 1


# 
# connection point pcs_transmit_clock
# 
add_interface pcs_transmit_clock clock end
set_interface_property pcs_transmit_clock clockRate 0
set_interface_property pcs_transmit_clock ENABLED true
set_interface_property pcs_transmit_clock EXPORT_OF ""
set_interface_property pcs_transmit_clock PORT_NAME_MAP ""
set_interface_property pcs_transmit_clock CMSIS_SVD_VARIABLES ""
set_interface_property pcs_transmit_clock SVD_ADDRESS_GROUP ""

add_interface_port pcs_transmit_clock pcs_tx_clk clk Input 1


# 
# connection point pcs_receive_clock
# 
add_interface pcs_receive_clock clock end
set_interface_property pcs_receive_clock clockRate 0
set_interface_property pcs_receive_clock ENABLED true
set_interface_property pcs_receive_clock EXPORT_OF ""
set_interface_property pcs_receive_clock PORT_NAME_MAP ""
set_interface_property pcs_receive_clock CMSIS_SVD_VARIABLES ""
set_interface_property pcs_receive_clock SVD_ADDRESS_GROUP ""

add_interface_port pcs_receive_clock pcs_rx_clk clk Input 1


# 
# connection point pcs_clock_enable
# 
add_interface pcs_clock_enable conduit end
set_interface_property pcs_clock_enable associatedClock ""
set_interface_property pcs_clock_enable associatedReset ""
set_interface_property pcs_clock_enable ENABLED true
set_interface_property pcs_clock_enable EXPORT_OF ""
set_interface_property pcs_clock_enable PORT_NAME_MAP ""
set_interface_property pcs_clock_enable CMSIS_SVD_VARIABLES ""
set_interface_property pcs_clock_enable SVD_ADDRESS_GROUP ""

add_interface_port pcs_clock_enable pcs_txclk_ena tx_clkena Input 1
add_interface_port pcs_clock_enable pcs_rxclk_ena rx_clkena Input 1


# 
# connection point pcs_gmii
# 
add_interface pcs_gmii conduit end
set_interface_property pcs_gmii associatedClock ""
set_interface_property pcs_gmii associatedReset ""
set_interface_property pcs_gmii ENABLED true
set_interface_property pcs_gmii EXPORT_OF ""
set_interface_property pcs_gmii PORT_NAME_MAP ""
set_interface_property pcs_gmii CMSIS_SVD_VARIABLES ""
set_interface_property pcs_gmii SVD_ADDRESS_GROUP ""

add_interface_port pcs_gmii pcs_gmii_rx_dv gmii_rx_dv Input 1
add_interface_port pcs_gmii pcs_gmii_rx_d gmii_rx_d Input 8
add_interface_port pcs_gmii pcs_gmii_rx_err gmii_rx_err Input 1
add_interface_port pcs_gmii pcs_gmii_tx_en gmii_tx_en Output 1
add_interface_port pcs_gmii pcs_gmii_tx_d gmii_tx_d Output 8
add_interface_port pcs_gmii pcs_gmii_tx_err gmii_tx_err Output 1


# 
# connection point pcs_mii
# 
add_interface pcs_mii conduit end
set_interface_property pcs_mii associatedClock ""
set_interface_property pcs_mii associatedReset ""
set_interface_property pcs_mii ENABLED true
set_interface_property pcs_mii EXPORT_OF ""
set_interface_property pcs_mii PORT_NAME_MAP ""
set_interface_property pcs_mii CMSIS_SVD_VARIABLES ""
set_interface_property pcs_mii SVD_ADDRESS_GROUP ""

add_interface_port pcs_mii pcs_mii_rx_dv mii_rx_dv Input 1
add_interface_port pcs_mii pcs_mii_rx_d mii_rx_d Input 4
add_interface_port pcs_mii pcs_mii_rx_err mii_rx_err Input 1
add_interface_port pcs_mii pcs_mii_col mii_col Input 1
add_interface_port pcs_mii pcs_mii_crs mii_crs Input 1
add_interface_port pcs_mii pcs_mii_tx_en mii_tx_en Output 1
add_interface_port pcs_mii pcs_mii_tx_d mii_tx_d Output 4
add_interface_port pcs_mii pcs_mii_tx_err mii_tx_err Output 1


## Add documentation links for user guide and/or release notes
add_documentation_link "User Guide" https://documentation.altera.com/#/link/sfo1400787952932/iga1434499254579
add_documentation_link "Release Notes" https://documentation.altera.com/#/link/hco1421698042087/hco1421698013408
